### PR TITLE
All tasks is done!

### PR DESCRIPTION
**Pull request by Edg4rV**
Tasks is done, please review

### CODE REVIEW

**Comment by Edg4rV** [comment]
Tasks is done!

**Comment by Edg4rV** [comment]
All Tasks is done!

**Comment by ShadowZ1xy** [comment]
Edgar jan du qo commitneric mekum Gevorgi grac arajadranqneri readme file-nes jnjum, ete djvar chi et commit@ cancel ara u noric pull request baci.

**Comment by Edg4rV** [comment]
ok Suren jan

**Pull request closed without merging**
